nombre = input("ingrese sus nombres")
apellidos =input("ingrese sus apellidos ")
edad =int(input("ingrese edad "))
estatura = float(input("Estatura (metros)"))
peso=float(input("Peso(kilogramos) "))
color0jos=(input("Color de ojos"))
colorCabello=(input("color de cabello"))
print("-"*20)
print("bienvenid@ %s %s. " %(nombre , apellidos))
print("Tienes %d años"%edad)
print("Tu estatura es %g. , tu peso es %g. "%(peso,estatura))
print("Y el color de sus ojos son %s. , y de su cabello es %s. "%(color0jos,colorCabello))
